#!/usr/bin/env bash

# This script # print new aliases, commands and shortcuts you've created
# I wrote this script because I make so many aliases and shortcuts, that I don't always remeber them all
# Edit this script according to whatever aliases and shortcut commands you create
# All text is printed in red as dictaed by: "\e[1;31m   \e[0m"
# You can use that ^^^ as a template for printing text in red,
# just place the text to print between these two "\e[1;31m   \e[0m"
# must be used with printf, Not echo
# example:
# printf "\e[1;31m text to print to the screen  \e[0m"
# -----------------------------------------------------------

echo ""
printf "\e[1;31m headers \e[0m"; echo ": List of HTTP request headers."

printf "\e[1;31m xfh \e[0m"; echo  ": List of X-Forwarded for headers."

printf "\e[1;31m stealcookies \e[0m"; echo ": XSS exploit code to steal cookies."

printf "\e[1;31m space \e[0m"; echo ": Double spaces lines of a text file."

printf "\e[1;31m remap \e[0m"; echo ": Remaps caps lock to the escape key."

printf "\e[1;31m gprac \e[0m"; echo  ": cd's to a practice dir for go lang."

printf "\e[1;31m showgoimports \e[0m"; echo  ": prints package main & imports for a .go file."

printf "\e[1;31m clte \e[0m"; echo  ": Content-Length Transfer-Encoding Req Smuggling template."

printf "\e[1;31m tecl \e[0m"; echo  ": Transfer-Encoding Content-Length template."

printf "\e[1;31m tete \e[0m"; echo  ": Transfer-Encoding Transfer-Encoding template."

printf "\e[1;31m mongodb-compass \e[0m"; echo ": Launch MongoDB desktop Client."

#printf "\e[1;31m <new cmd here> \e[0m"; echo  ": <what new cmd does> "

printf "\e[1;31m webstorm \e[0m"; echo ": Opens the WbStorm IDE."

printf "\e[1;31m gol \e[0m"; echo  ": Launches the GoLand IDE"

printf "\e[1;31m idea \e[0m"; echo  ": Launches the IntelliJ Python IDE  "

# Templates for additional entries
#printf "\e[1;31m <new cmd here> \e[0m"; echo  ": <what new cmd does> "
#printf "\e[1;31m <new cmd here> \e[0m"; echo  ": <what new cmd does> "
#printf "\e[1;31m <new cmd here> \e[0m"; echo  ": <what new cmd does> "
#printf "\e[1;31m <new cmd here> \e[0m"; echo  ": <what new cmd does> "

echo ""

echo " A copy of this is kept as a dot file in the home directory."

echo""

