#!/bin/bash

# Instantly Create & chmod either a Python or Bash file/script.
# Make sure the script is being executed with sudo privileges.
if [[ "${UID}" -ne 0 ]]
then
   echo 'Please run with sudo or as root.'
   exit 1
fi

# Create either a Python, Bash, text file or a .md & open it with Vim
echo -e "Select a filetype to create: Python, Bash, txt, or .md: \n1 = Python\n2 = Bash\n3 = txt\n4 = Markdown Doc File"
read sel

# Crete a Python file/script
if [[ $sel -eq 1 ]];
then
    echo "Name the Python file: "
    read NAME
touch $NAME.py
echo "#!/usr/bin/env python3" > $NAME.py
chmod +x $NAME.py
vim $NAME.py

# Create a Bash Script
elif [[ $sel -eq 2 ]];
then
    echo "Name the Bash script: "
    read NAME
touch $NAME.sh
echo "#!/bin/bash" > $NAME.sh
chmod 755 $NAME.sh
vim $NAME.sh

# Create a .txt file
elif [[ $sel -eq 3 ]];
then
    echo "Name the text file: "
    read NAME
touch $NAME.txt
echo "# ASCII Text" > $NAME.txt
vim $NAME.txt

# Create a Markdown Documentation file
elif [[ $sel -eq 4 ]];
then
    echo "Name the Markdown Documentation file: "
    read NAME
touch $NAME.md
echo "# Markdown Document" > $NAME.md
vim $NAME.md


exit 0
fi

