#!/usr/bin/env bash

# Content Length Transfer Encoding template
# chmod +x this script, then move it to /usr/bin for quick template echo onto the screen

printf "\e[1;31m POST / HTTP/1.1 \e[0m\n"
printf "\e[1;31m Host:  \e[0m\n"
printf "\e[1;31m Content-Type: application/x-www-form-urlencoded \e[0m\n"
printf "\e[1;31m Content-Length:  \e[0m\n"
printf "\e[1;31m Transfer-Encoding: chunked \e[0m\n"
echo ""
printf "\e[1;31m 3\e[0m\n"
printf "\e[1;31m x=x\e[0m\n"
printf "\e[1;31m 0\e[0m\n\n"
printf "\e[1;31m GET / HTTP/1.1 \e[0m\n"
printf "\e[1;31m Host:  \e[0m\n"
printf "\e[1;31m Foo: x  \e[0m\n"
