#!/usr/bin/env python3

# Be sure to place 1141-headers.txt in /usr/bin, (your path), along with this python script

filename = "/usr/bin/headers.txt"

with open(filename) as file_object:
    for line in file_object:
        print(line.rstrip())
